services:
  - type: web
    name: wave-app
    env: docker
    region: frankfurt
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: APP_NAME
        value: Wave
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: wave-app
          property: host
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: wave-db
          property: connectionString
      - key: CLOUDINARY_URL
        sync: false
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_TOKEN
        sync: false
      - key: TWILIO_SENDER
        sync: false

databases:
  - name: wave-db
    plan: free
    ipAllowList: []